### ISSUE TITLE
Right and Left disparity map

### ISSUE THREAD

**Issue by ghost** [LinHungShi/GCNetwork#11]
Hi,Is it possible to get disparity of both left and right image instead of one disparity ?
In case it doesn't can anyone suggest me a way to get both disparities from output disparity
thanks in advance

**Comment by LinHungShi** [comment]
Hi, since the model only outputs one disparity map, you wouldn't be able to get left and right disparity map. However, you can train the model with both left and right disparities to reduce inconsistency problem.
