### ISSUE TITLE
About the Unary features

### ISSUE THREAD

**Issue by Tenacity-soar** [LinHungShi/GCNetwork#7]
In the paper, the 3.1 talked about the Unary features, they used eight residual blocks.  But in the code, the NUM_RES = 5, only loop 6 times . Is this mean that the code used six residual blocks?

**Comment by LinHungShi** [comment]
Yes, you can adjust NUM_RES to any number as you want. I did it because the model was too large  to fit in memory.

**Comment by LinHungShi** [comment]
The repository has been updated. Please check it.
